image: alpine/edge
packages:
- ruby
- ruby-dev
- rsync
sources:
- https://git.sr.ht/~bt/wruby
secrets:
- 07201d32-1451-4a8f-9bff-ce8b2232c67d
tasks:
- install-gems: |
    sudo gem install 'kramdown:2.4.0' 'rss:0.3.0'
- build: |
    cd wruby
    sudo make build
- deploy-blog: |
    cd wruby
    rsync --rsh="ssh -o StrictHostKeyChecking=no -i ~/.ssh/07201d32-1451-4a8f-9bff-ce8b2232c67d" -rzP build/ bt@wruby.btxx.org:/var/www/wruby
